apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: "greenlogistics-ca"
spec:
  tls:
    - hosts:
        - grafana.greenlogistics.local
      secretName: grafana-tls
  rules:
    - host: grafana.greenlogistics.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 80
