apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: monitoring
type: Opaque
# Générer avec : kubectl create secret generic grafana-admin -n monitoring --from-literal=password='VOTRE_MOT_DE_PASSE'
data: {}
